name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to GitHub Packages Docker registry
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/ollama-model-size-filter:latest .

    # Push the Docker image to GitHub Packages
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/ollama-model-size-filter:latest
